### ISSUE TITLE
User can type a letter and get feedback.

### ISSUE THREAD

**Issue by kevinhyder** [kevinhyder/typing-test#5]
# Motivation
Allow the user to clearly see and follow their progress throughout the test.

# Task List
- [x] Add keypress event listener.
- [x] Write function to compare the key pressed to the current character to type.
- [x] If correct add specified CSS properties and move to the next character.
- [x] If incorrect add specified CSS properties and remain.

**Comment by kevinhyder** [comment]
![screen shot 2017-06-12 at 11 02 50 am](https://user-images.githubusercontent.com/29046239/27047993-f08196b0-4f5e-11e7-9a53-8a5dea99ed7f.png)
